on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-prg-helloworld:
    runs-on: ubuntu-latest
    container: 
      image: z88dk/z88dk

    steps:
    - uses: actions/checkout@v3
    - name: Build helloworld PRG
      run: |
        cd src/helloworld
        sed -i 's/node[[:digit:]]\+/node2000000/g' Makefile
        make
        ls -alh
    - name: Upload HELLOWORLD.BIN
      uses: actions/upload-artifact@v4
      with:
        name: HELLOWORLD-UNSIGNED.PRG
        path: src/helloworld/HELLOWORLD.PRG

  sign-prg-helloworld:
    runs-on: ubuntu-latest
    needs: [build-prg-helloworld]
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install -y python3
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: HELLOWORLD-UNSIGNED.PRG
        path: ./
    - name: Sign binary
      run: |
        python3 scripts/signprg.py HELLOWORLD.PRG
    - name: Upload HELLOWORLD.PRG
      uses: actions/upload-artifact@v4
      with:
        name: HELLOWORLD.PRG
        path: HELLOWORLD.PRG

#-------------------------------------------------------------------------------

  build-prg-moncrc16:
    runs-on: ubuntu-latest
    container: 
      image: z88dk/z88dk

    steps:
    - uses: actions/checkout@v3
    - name: Build CRC16 PRG
      run: |
        cd src/crcmonitor
        sed -i 's/node[[:digit:]]\+/node2000000/g' Makefile
        make
        ls -alh
    - name: Upload MONCRC16.BIN
      uses: actions/upload-artifact@v4
      with:
        name: MONCRC16-UNSIGNED.PRG
        path: src/crcmonitor/MONCRC16.PRG

  sign-prg-moncrc16:
    runs-on: ubuntu-latest
    needs: [build-prg-moncrc16]
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install -y python3
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: MONCRC16-UNSIGNED.PRG
        path: ./
    - name: Sign binary
      run: |
        python3 scripts/signprg.py MONCRC16.PRG
    - name: Upload MONCRC16.PRG
      uses: actions/upload-artifact@v4
      with:
        name: MONCRC16.PRG
        path: MONCRC16.PRG

#-------------------------------------------------------------------------------

  build-prg-casdump:
    runs-on: ubuntu-latest
    container: 
      image: z88dk/z88dk

    steps:
    - uses: actions/checkout@v3
    - name: Build CRC16 PRG
      run: |
        cd src/casdump
        sed -i 's/node[[:digit:]]\+/node2000000/g' Makefile
        make cassettedump-prg
        mv -v CASDUMP.PRG CASDUMP.PRG
    - name: Upload CASDUMP.BIN
      uses: actions/upload-artifact@v4
      with:
        name: CASDUMP-UNSIGNED.PRG
        path: src/casdump/CASDUMP.PRG

  sign-prg-casdump:
    runs-on: ubuntu-latest
    needs: [build-prg-casdump]
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install -y python3
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: CASDUMP-UNSIGNED.PRG
        path: ./
    - name: Sign binary
      run: |
        python3 scripts/signprg.py CASDUMP.PRG
    - name: Upload CASDUMP.PRG
      uses: actions/upload-artifact@v4
      with:
        name: CASDUMP.PRG
        path: CASDUMP.PRG

#-------------------------------------------------------------------------------

  deploy:
    runs-on: ubuntu-latest
    needs: [sign-prg-helloworld, sign-prg-moncrc16, sign-prg-casdump]
    permissions: write-all
    steps:
    - name: Download MONCRC16
      uses: actions/download-artifact@v4
      with:
        name: MONCRC16.PRG
        path: ./
    - name: Download CASDUMP
      uses: actions/download-artifact@v4
      with:
        name: CASDUMP.PRG
        path: ./
    - name: Download HELLOWORLD.PRG
      uses: actions/download-artifact@v4
      with:
        name: HELLOWORLD.PRG
        path: ./
    - name: Update the nightly release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            CASDUMP.PRG
            MONCRC16.PRG
            HELLOWORLD.PRG
          tag_name: latest
          release_name: Latest Build
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}